/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorIndexRouteImport } from './routes/creator.index'
import { Route as BrandIndexRouteImport } from './routes/brand.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OnboardingCreatorRouteImport } from './routes/onboarding.creator'
import { Route as OnboardingBrandRouteImport } from './routes/onboarding.brand'
import { Route as CreatorWalletRouteImport } from './routes/creator.wallet'
import { Route as CreatorTipsRouteImport } from './routes/creator.tips'
import { Route as CreatorSupportRouteImport } from './routes/creator.support'
import { Route as CreatorSubmissionsRouteImport } from './routes/creator.submissions'
import { Route as CreatorSettingsRouteImport } from './routes/creator.settings'
import { Route as CreatorReferralsRouteImport } from './routes/creator.referrals'
import { Route as CreatorProfileRouteImport } from './routes/creator.profile'
import { Route as CreatorNotificationsRouteImport } from './routes/creator.notifications'
import { Route as CreatorHowItWorksRouteImport } from './routes/creator.how-it-works'
import { Route as CreatorEarningsRouteImport } from './routes/creator.earnings'
import { Route as CreatorCampaignsRouteImport } from './routes/creator.campaigns'
import { Route as CreatorAnalyticsRouteImport } from './routes/creator.analytics'
import { Route as BrandWalletRouteImport } from './routes/brand.wallet'
import { Route as BrandSupportRouteImport } from './routes/brand.support'
import { Route as BrandSubmissionsRouteImport } from './routes/brand.submissions'
import { Route as BrandSettingsRouteImport } from './routes/brand.settings'
import { Route as BrandProfileRouteImport } from './routes/brand.profile'
import { Route as BrandNotificationsRouteImport } from './routes/brand.notifications'
import { Route as BrandHowItWorksRouteImport } from './routes/brand.how-it-works'
import { Route as BrandCreateRouteImport } from './routes/brand.create'
import { Route as BrandCampaignsRouteImport } from './routes/brand.campaigns'
import { Route as BrandAnalyticsRouteImport } from './routes/brand.analytics'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminExamplesRouteImport } from './routes/admin.examples'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as BrandCampaignsIndexRouteImport } from './routes/brand.campaigns.index'
import { Route as BrandAnalyticsIndexRouteImport } from './routes/brand.analytics.index'
import { Route as CreatorCampaignsIdRouteImport } from './routes/creator.campaigns.$id'
import { Route as BrandCreateTypeRouteImport } from './routes/brand.create.$type'
import { Route as BrandCampaignsIdRouteImport } from './routes/brand.campaigns.$id'
import { Route as BrandAnalyticsIdRouteImport } from './routes/brand.analytics.$id'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const BrandIndexRoute = BrandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OnboardingCreatorRoute = OnboardingCreatorRouteImport.update({
  id: '/onboarding/creator',
  path: '/onboarding/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBrandRoute = OnboardingBrandRouteImport.update({
  id: '/onboarding/brand',
  path: '/onboarding/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorWalletRoute = CreatorWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorTipsRoute = CreatorTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorSupportRoute = CreatorSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorSubmissionsRoute = CreatorSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorSettingsRoute = CreatorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorReferralsRoute = CreatorReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorProfileRoute = CreatorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorNotificationsRoute = CreatorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorHowItWorksRoute = CreatorHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorEarningsRoute = CreatorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorCampaignsRoute = CreatorCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorAnalyticsRoute = CreatorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CreatorRoute,
} as any)
const BrandWalletRoute = BrandWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => BrandRoute,
} as any)
const BrandSupportRoute = BrandSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => BrandRoute,
} as any)
const BrandSubmissionsRoute = BrandSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => BrandRoute,
} as any)
const BrandSettingsRoute = BrandSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BrandRoute,
} as any)
const BrandProfileRoute = BrandProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BrandRoute,
} as any)
const BrandNotificationsRoute = BrandNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => BrandRoute,
} as any)
const BrandHowItWorksRoute = BrandHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => BrandRoute,
} as any)
const BrandCreateRoute = BrandCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => BrandRoute,
} as any)
const BrandCampaignsRoute = BrandCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => BrandRoute,
} as any)
const BrandAnalyticsRoute = BrandAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BrandRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamplesRoute = AdminExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const BrandCampaignsIndexRoute = BrandCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandCampaignsRoute,
} as any)
const BrandAnalyticsIndexRoute = BrandAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandAnalyticsRoute,
} as any)
const CreatorCampaignsIdRoute = CreatorCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CreatorCampaignsRoute,
} as any)
const BrandCreateTypeRoute = BrandCreateTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => BrandCreateRoute,
} as any)
const BrandCampaignsIdRoute = BrandCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BrandCampaignsRoute,
} as any)
const BrandAnalyticsIdRoute = BrandAnalyticsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BrandAnalyticsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/brand': typeof BrandRouteWithChildren
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/licenses': typeof LicensesRoute
  '/login': typeof LoginRoute
  '/schedule': typeof ScheduleRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/examples': typeof AdminExamplesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brand/analytics': typeof BrandAnalyticsRouteWithChildren
  '/brand/campaigns': typeof BrandCampaignsRouteWithChildren
  '/brand/create': typeof BrandCreateRouteWithChildren
  '/brand/how-it-works': typeof BrandHowItWorksRoute
  '/brand/notifications': typeof BrandNotificationsRoute
  '/brand/profile': typeof BrandProfileRoute
  '/brand/settings': typeof BrandSettingsRoute
  '/brand/submissions': typeof BrandSubmissionsRoute
  '/brand/support': typeof BrandSupportRoute
  '/brand/wallet': typeof BrandWalletRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/campaigns': typeof CreatorCampaignsRouteWithChildren
  '/creator/earnings': typeof CreatorEarningsRoute
  '/creator/how-it-works': typeof CreatorHowItWorksRoute
  '/creator/notifications': typeof CreatorNotificationsRoute
  '/creator/profile': typeof CreatorProfileRoute
  '/creator/referrals': typeof CreatorReferralsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/submissions': typeof CreatorSubmissionsRoute
  '/creator/support': typeof CreatorSupportRoute
  '/creator/tips': typeof CreatorTipsRoute
  '/creator/wallet': typeof CreatorWalletRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/creator': typeof OnboardingCreatorRoute
  '/admin/': typeof AdminIndexRoute
  '/brand/': typeof BrandIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/brand/analytics/$id': typeof BrandAnalyticsIdRoute
  '/brand/campaigns/$id': typeof BrandCampaignsIdRoute
  '/brand/create/$type': typeof BrandCreateTypeRoute
  '/creator/campaigns/$id': typeof CreatorCampaignsIdRoute
  '/brand/analytics/': typeof BrandAnalyticsIndexRoute
  '/brand/campaigns/': typeof BrandCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/get-started': typeof GetStartedRoute
  '/licenses': typeof LicensesRoute
  '/login': typeof LoginRoute
  '/schedule': typeof ScheduleRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/examples': typeof AdminExamplesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brand/create': typeof BrandCreateRouteWithChildren
  '/brand/how-it-works': typeof BrandHowItWorksRoute
  '/brand/notifications': typeof BrandNotificationsRoute
  '/brand/profile': typeof BrandProfileRoute
  '/brand/settings': typeof BrandSettingsRoute
  '/brand/submissions': typeof BrandSubmissionsRoute
  '/brand/support': typeof BrandSupportRoute
  '/brand/wallet': typeof BrandWalletRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/campaigns': typeof CreatorCampaignsRouteWithChildren
  '/creator/earnings': typeof CreatorEarningsRoute
  '/creator/how-it-works': typeof CreatorHowItWorksRoute
  '/creator/notifications': typeof CreatorNotificationsRoute
  '/creator/profile': typeof CreatorProfileRoute
  '/creator/referrals': typeof CreatorReferralsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/submissions': typeof CreatorSubmissionsRoute
  '/creator/support': typeof CreatorSupportRoute
  '/creator/tips': typeof CreatorTipsRoute
  '/creator/wallet': typeof CreatorWalletRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/creator': typeof OnboardingCreatorRoute
  '/admin': typeof AdminIndexRoute
  '/brand': typeof BrandIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/brand/analytics/$id': typeof BrandAnalyticsIdRoute
  '/brand/campaigns/$id': typeof BrandCampaignsIdRoute
  '/brand/create/$type': typeof BrandCreateTypeRoute
  '/creator/campaigns/$id': typeof CreatorCampaignsIdRoute
  '/brand/analytics': typeof BrandAnalyticsIndexRoute
  '/brand/campaigns': typeof BrandCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/brand': typeof BrandRouteWithChildren
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/licenses': typeof LicensesRoute
  '/login': typeof LoginRoute
  '/schedule': typeof ScheduleRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/examples': typeof AdminExamplesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brand/analytics': typeof BrandAnalyticsRouteWithChildren
  '/brand/campaigns': typeof BrandCampaignsRouteWithChildren
  '/brand/create': typeof BrandCreateRouteWithChildren
  '/brand/how-it-works': typeof BrandHowItWorksRoute
  '/brand/notifications': typeof BrandNotificationsRoute
  '/brand/profile': typeof BrandProfileRoute
  '/brand/settings': typeof BrandSettingsRoute
  '/brand/submissions': typeof BrandSubmissionsRoute
  '/brand/support': typeof BrandSupportRoute
  '/brand/wallet': typeof BrandWalletRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/campaigns': typeof CreatorCampaignsRouteWithChildren
  '/creator/earnings': typeof CreatorEarningsRoute
  '/creator/how-it-works': typeof CreatorHowItWorksRoute
  '/creator/notifications': typeof CreatorNotificationsRoute
  '/creator/profile': typeof CreatorProfileRoute
  '/creator/referrals': typeof CreatorReferralsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/submissions': typeof CreatorSubmissionsRoute
  '/creator/support': typeof CreatorSupportRoute
  '/creator/tips': typeof CreatorTipsRoute
  '/creator/wallet': typeof CreatorWalletRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/creator': typeof OnboardingCreatorRoute
  '/admin/': typeof AdminIndexRoute
  '/brand/': typeof BrandIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/brand/analytics/$id': typeof BrandAnalyticsIdRoute
  '/brand/campaigns/$id': typeof BrandCampaignsIdRoute
  '/brand/create/$type': typeof BrandCreateTypeRoute
  '/creator/campaigns/$id': typeof CreatorCampaignsIdRoute
  '/brand/analytics/': typeof BrandAnalyticsIndexRoute
  '/brand/campaigns/': typeof BrandCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/brand'
    | '/contact'
    | '/creator'
    | '/get-started'
    | '/licenses'
    | '/login'
    | '/schedule'
    | '/admin/analytics'
    | '/admin/campaigns'
    | '/admin/config'
    | '/admin/disputes'
    | '/admin/examples'
    | '/admin/invoices'
    | '/admin/moderation'
    | '/admin/submissions'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/wallet'
    | '/blog/$slug'
    | '/brand/analytics'
    | '/brand/campaigns'
    | '/brand/create'
    | '/brand/how-it-works'
    | '/brand/notifications'
    | '/brand/profile'
    | '/brand/settings'
    | '/brand/submissions'
    | '/brand/support'
    | '/brand/wallet'
    | '/creator/analytics'
    | '/creator/campaigns'
    | '/creator/earnings'
    | '/creator/how-it-works'
    | '/creator/notifications'
    | '/creator/profile'
    | '/creator/referrals'
    | '/creator/settings'
    | '/creator/submissions'
    | '/creator/support'
    | '/creator/tips'
    | '/creator/wallet'
    | '/onboarding/brand'
    | '/onboarding/creator'
    | '/admin/'
    | '/brand/'
    | '/creator/'
    | '/brand/analytics/$id'
    | '/brand/campaigns/$id'
    | '/brand/create/$type'
    | '/creator/campaigns/$id'
    | '/brand/analytics/'
    | '/brand/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/get-started'
    | '/licenses'
    | '/login'
    | '/schedule'
    | '/admin/analytics'
    | '/admin/campaigns'
    | '/admin/config'
    | '/admin/disputes'
    | '/admin/examples'
    | '/admin/invoices'
    | '/admin/moderation'
    | '/admin/submissions'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/wallet'
    | '/blog/$slug'
    | '/brand/create'
    | '/brand/how-it-works'
    | '/brand/notifications'
    | '/brand/profile'
    | '/brand/settings'
    | '/brand/submissions'
    | '/brand/support'
    | '/brand/wallet'
    | '/creator/analytics'
    | '/creator/campaigns'
    | '/creator/earnings'
    | '/creator/how-it-works'
    | '/creator/notifications'
    | '/creator/profile'
    | '/creator/referrals'
    | '/creator/settings'
    | '/creator/submissions'
    | '/creator/support'
    | '/creator/tips'
    | '/creator/wallet'
    | '/onboarding/brand'
    | '/onboarding/creator'
    | '/admin'
    | '/brand'
    | '/creator'
    | '/brand/analytics/$id'
    | '/brand/campaigns/$id'
    | '/brand/create/$type'
    | '/creator/campaigns/$id'
    | '/brand/analytics'
    | '/brand/campaigns'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/brand'
    | '/contact'
    | '/creator'
    | '/get-started'
    | '/licenses'
    | '/login'
    | '/schedule'
    | '/admin/analytics'
    | '/admin/campaigns'
    | '/admin/config'
    | '/admin/disputes'
    | '/admin/examples'
    | '/admin/invoices'
    | '/admin/moderation'
    | '/admin/submissions'
    | '/admin/support'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/wallet'
    | '/blog/$slug'
    | '/brand/analytics'
    | '/brand/campaigns'
    | '/brand/create'
    | '/brand/how-it-works'
    | '/brand/notifications'
    | '/brand/profile'
    | '/brand/settings'
    | '/brand/submissions'
    | '/brand/support'
    | '/brand/wallet'
    | '/creator/analytics'
    | '/creator/campaigns'
    | '/creator/earnings'
    | '/creator/how-it-works'
    | '/creator/notifications'
    | '/creator/profile'
    | '/creator/referrals'
    | '/creator/settings'
    | '/creator/submissions'
    | '/creator/support'
    | '/creator/tips'
    | '/creator/wallet'
    | '/onboarding/brand'
    | '/onboarding/creator'
    | '/admin/'
    | '/brand/'
    | '/creator/'
    | '/brand/analytics/$id'
    | '/brand/campaigns/$id'
    | '/brand/create/$type'
    | '/creator/campaigns/$id'
    | '/brand/analytics/'
    | '/brand/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  BrandRoute: typeof BrandRouteWithChildren
  ContactRoute: typeof ContactRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  GetStartedRoute: typeof GetStartedRoute
  LicensesRoute: typeof LicensesRoute
  LoginRoute: typeof LoginRoute
  ScheduleRoute: typeof ScheduleRoute
  OnboardingBrandRoute: typeof OnboardingBrandRoute
  OnboardingCreatorRoute: typeof OnboardingCreatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/brand/': {
      id: '/brand/'
      path: '/'
      fullPath: '/brand/'
      preLoaderRoute: typeof BrandIndexRouteImport
      parentRoute: typeof BrandRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/onboarding/creator': {
      id: '/onboarding/creator'
      path: '/onboarding/creator'
      fullPath: '/onboarding/creator'
      preLoaderRoute: typeof OnboardingCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/brand': {
      id: '/onboarding/brand'
      path: '/onboarding/brand'
      fullPath: '/onboarding/brand'
      preLoaderRoute: typeof OnboardingBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/wallet': {
      id: '/creator/wallet'
      path: '/wallet'
      fullPath: '/creator/wallet'
      preLoaderRoute: typeof CreatorWalletRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/tips': {
      id: '/creator/tips'
      path: '/tips'
      fullPath: '/creator/tips'
      preLoaderRoute: typeof CreatorTipsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/support': {
      id: '/creator/support'
      path: '/support'
      fullPath: '/creator/support'
      preLoaderRoute: typeof CreatorSupportRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/submissions': {
      id: '/creator/submissions'
      path: '/submissions'
      fullPath: '/creator/submissions'
      preLoaderRoute: typeof CreatorSubmissionsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/settings': {
      id: '/creator/settings'
      path: '/settings'
      fullPath: '/creator/settings'
      preLoaderRoute: typeof CreatorSettingsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/referrals': {
      id: '/creator/referrals'
      path: '/referrals'
      fullPath: '/creator/referrals'
      preLoaderRoute: typeof CreatorReferralsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/profile': {
      id: '/creator/profile'
      path: '/profile'
      fullPath: '/creator/profile'
      preLoaderRoute: typeof CreatorProfileRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/notifications': {
      id: '/creator/notifications'
      path: '/notifications'
      fullPath: '/creator/notifications'
      preLoaderRoute: typeof CreatorNotificationsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/how-it-works': {
      id: '/creator/how-it-works'
      path: '/how-it-works'
      fullPath: '/creator/how-it-works'
      preLoaderRoute: typeof CreatorHowItWorksRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/earnings': {
      id: '/creator/earnings'
      path: '/earnings'
      fullPath: '/creator/earnings'
      preLoaderRoute: typeof CreatorEarningsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/campaigns': {
      id: '/creator/campaigns'
      path: '/campaigns'
      fullPath: '/creator/campaigns'
      preLoaderRoute: typeof CreatorCampaignsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/analytics': {
      id: '/creator/analytics'
      path: '/analytics'
      fullPath: '/creator/analytics'
      preLoaderRoute: typeof CreatorAnalyticsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/brand/wallet': {
      id: '/brand/wallet'
      path: '/wallet'
      fullPath: '/brand/wallet'
      preLoaderRoute: typeof BrandWalletRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/support': {
      id: '/brand/support'
      path: '/support'
      fullPath: '/brand/support'
      preLoaderRoute: typeof BrandSupportRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/submissions': {
      id: '/brand/submissions'
      path: '/submissions'
      fullPath: '/brand/submissions'
      preLoaderRoute: typeof BrandSubmissionsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/settings': {
      id: '/brand/settings'
      path: '/settings'
      fullPath: '/brand/settings'
      preLoaderRoute: typeof BrandSettingsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/profile': {
      id: '/brand/profile'
      path: '/profile'
      fullPath: '/brand/profile'
      preLoaderRoute: typeof BrandProfileRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/notifications': {
      id: '/brand/notifications'
      path: '/notifications'
      fullPath: '/brand/notifications'
      preLoaderRoute: typeof BrandNotificationsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/how-it-works': {
      id: '/brand/how-it-works'
      path: '/how-it-works'
      fullPath: '/brand/how-it-works'
      preLoaderRoute: typeof BrandHowItWorksRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/create': {
      id: '/brand/create'
      path: '/create'
      fullPath: '/brand/create'
      preLoaderRoute: typeof BrandCreateRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/campaigns': {
      id: '/brand/campaigns'
      path: '/campaigns'
      fullPath: '/brand/campaigns'
      preLoaderRoute: typeof BrandCampaignsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/analytics': {
      id: '/brand/analytics'
      path: '/analytics'
      fullPath: '/brand/analytics'
      preLoaderRoute: typeof BrandAnalyticsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/examples': {
      id: '/admin/examples'
      path: '/examples'
      fullPath: '/admin/examples'
      preLoaderRoute: typeof AdminExamplesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/brand/campaigns/': {
      id: '/brand/campaigns/'
      path: '/'
      fullPath: '/brand/campaigns/'
      preLoaderRoute: typeof BrandCampaignsIndexRouteImport
      parentRoute: typeof BrandCampaignsRoute
    }
    '/brand/analytics/': {
      id: '/brand/analytics/'
      path: '/'
      fullPath: '/brand/analytics/'
      preLoaderRoute: typeof BrandAnalyticsIndexRouteImport
      parentRoute: typeof BrandAnalyticsRoute
    }
    '/creator/campaigns/$id': {
      id: '/creator/campaigns/$id'
      path: '/$id'
      fullPath: '/creator/campaigns/$id'
      preLoaderRoute: typeof CreatorCampaignsIdRouteImport
      parentRoute: typeof CreatorCampaignsRoute
    }
    '/brand/create/$type': {
      id: '/brand/create/$type'
      path: '/$type'
      fullPath: '/brand/create/$type'
      preLoaderRoute: typeof BrandCreateTypeRouteImport
      parentRoute: typeof BrandCreateRoute
    }
    '/brand/campaigns/$id': {
      id: '/brand/campaigns/$id'
      path: '/$id'
      fullPath: '/brand/campaigns/$id'
      preLoaderRoute: typeof BrandCampaignsIdRouteImport
      parentRoute: typeof BrandCampaignsRoute
    }
    '/brand/analytics/$id': {
      id: '/brand/analytics/$id'
      path: '/$id'
      fullPath: '/brand/analytics/$id'
      preLoaderRoute: typeof BrandAnalyticsIdRouteImport
      parentRoute: typeof BrandAnalyticsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminExamplesRoute: typeof AdminExamplesRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminExamplesRoute: AdminExamplesRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface BrandAnalyticsRouteChildren {
  BrandAnalyticsIdRoute: typeof BrandAnalyticsIdRoute
  BrandAnalyticsIndexRoute: typeof BrandAnalyticsIndexRoute
}

const BrandAnalyticsRouteChildren: BrandAnalyticsRouteChildren = {
  BrandAnalyticsIdRoute: BrandAnalyticsIdRoute,
  BrandAnalyticsIndexRoute: BrandAnalyticsIndexRoute,
}

const BrandAnalyticsRouteWithChildren = BrandAnalyticsRoute._addFileChildren(
  BrandAnalyticsRouteChildren,
)

interface BrandCampaignsRouteChildren {
  BrandCampaignsIdRoute: typeof BrandCampaignsIdRoute
  BrandCampaignsIndexRoute: typeof BrandCampaignsIndexRoute
}

const BrandCampaignsRouteChildren: BrandCampaignsRouteChildren = {
  BrandCampaignsIdRoute: BrandCampaignsIdRoute,
  BrandCampaignsIndexRoute: BrandCampaignsIndexRoute,
}

const BrandCampaignsRouteWithChildren = BrandCampaignsRoute._addFileChildren(
  BrandCampaignsRouteChildren,
)

interface BrandCreateRouteChildren {
  BrandCreateTypeRoute: typeof BrandCreateTypeRoute
}

const BrandCreateRouteChildren: BrandCreateRouteChildren = {
  BrandCreateTypeRoute: BrandCreateTypeRoute,
}

const BrandCreateRouteWithChildren = BrandCreateRoute._addFileChildren(
  BrandCreateRouteChildren,
)

interface BrandRouteChildren {
  BrandAnalyticsRoute: typeof BrandAnalyticsRouteWithChildren
  BrandCampaignsRoute: typeof BrandCampaignsRouteWithChildren
  BrandCreateRoute: typeof BrandCreateRouteWithChildren
  BrandHowItWorksRoute: typeof BrandHowItWorksRoute
  BrandNotificationsRoute: typeof BrandNotificationsRoute
  BrandProfileRoute: typeof BrandProfileRoute
  BrandSettingsRoute: typeof BrandSettingsRoute
  BrandSubmissionsRoute: typeof BrandSubmissionsRoute
  BrandSupportRoute: typeof BrandSupportRoute
  BrandWalletRoute: typeof BrandWalletRoute
  BrandIndexRoute: typeof BrandIndexRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandAnalyticsRoute: BrandAnalyticsRouteWithChildren,
  BrandCampaignsRoute: BrandCampaignsRouteWithChildren,
  BrandCreateRoute: BrandCreateRouteWithChildren,
  BrandHowItWorksRoute: BrandHowItWorksRoute,
  BrandNotificationsRoute: BrandNotificationsRoute,
  BrandProfileRoute: BrandProfileRoute,
  BrandSettingsRoute: BrandSettingsRoute,
  BrandSubmissionsRoute: BrandSubmissionsRoute,
  BrandSupportRoute: BrandSupportRoute,
  BrandWalletRoute: BrandWalletRoute,
  BrandIndexRoute: BrandIndexRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

interface CreatorCampaignsRouteChildren {
  CreatorCampaignsIdRoute: typeof CreatorCampaignsIdRoute
}

const CreatorCampaignsRouteChildren: CreatorCampaignsRouteChildren = {
  CreatorCampaignsIdRoute: CreatorCampaignsIdRoute,
}

const CreatorCampaignsRouteWithChildren =
  CreatorCampaignsRoute._addFileChildren(CreatorCampaignsRouteChildren)

interface CreatorRouteChildren {
  CreatorAnalyticsRoute: typeof CreatorAnalyticsRoute
  CreatorCampaignsRoute: typeof CreatorCampaignsRouteWithChildren
  CreatorEarningsRoute: typeof CreatorEarningsRoute
  CreatorHowItWorksRoute: typeof CreatorHowItWorksRoute
  CreatorNotificationsRoute: typeof CreatorNotificationsRoute
  CreatorProfileRoute: typeof CreatorProfileRoute
  CreatorReferralsRoute: typeof CreatorReferralsRoute
  CreatorSettingsRoute: typeof CreatorSettingsRoute
  CreatorSubmissionsRoute: typeof CreatorSubmissionsRoute
  CreatorSupportRoute: typeof CreatorSupportRoute
  CreatorTipsRoute: typeof CreatorTipsRoute
  CreatorWalletRoute: typeof CreatorWalletRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorAnalyticsRoute: CreatorAnalyticsRoute,
  CreatorCampaignsRoute: CreatorCampaignsRouteWithChildren,
  CreatorEarningsRoute: CreatorEarningsRoute,
  CreatorHowItWorksRoute: CreatorHowItWorksRoute,
  CreatorNotificationsRoute: CreatorNotificationsRoute,
  CreatorProfileRoute: CreatorProfileRoute,
  CreatorReferralsRoute: CreatorReferralsRoute,
  CreatorSettingsRoute: CreatorSettingsRoute,
  CreatorSubmissionsRoute: CreatorSubmissionsRoute,
  CreatorSupportRoute: CreatorSupportRoute,
  CreatorTipsRoute: CreatorTipsRoute,
  CreatorWalletRoute: CreatorWalletRoute,
  CreatorIndexRoute: CreatorIndexRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  BrandRoute: BrandRouteWithChildren,
  ContactRoute: ContactRoute,
  CreatorRoute: CreatorRouteWithChildren,
  GetStartedRoute: GetStartedRoute,
  LicensesRoute: LicensesRoute,
  LoginRoute: LoginRoute,
  ScheduleRoute: ScheduleRoute,
  OnboardingBrandRoute: OnboardingBrandRoute,
  OnboardingCreatorRoute: OnboardingCreatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
